// EPS en Colombia
export const EPS_COLOMBIA = [
  "Sura EPS",
  "Nueva EPS",
  "Sanitas EPS",
  "Compensar EPS",
  "Famisanar EPS",
  "Salud Total EPS",
  "Coomeva EPS",
  "Aliansalud EPS",
  "Mutual Ser EPS",
  "Coosalud EPS",
  "Emssanar EPS",
  "Capital Salud EPS",
  "Savia Salud EPS",
  "Dusakawi EPS",
  "Asmet Salud EPS",
  "Mallamas EPS",
  "Pijaos Salud EPS",
  "Asociacion Indigena del Cauca EPS",
  "Anas Wayuu EPS",
  "Cajacopi EPS",
  "Comfachoco EPS",
  "Comfaoriente EPS",
  "Comfasucre EPS",
  "EPS Familiar de Colombia",
];

// AFP (Fondos de Pensiones) en Colombia
export const AFP_COLOMBIA = [
  "Porvenir",
  "Proteccion",
  "Colfondos",
  "Skandia",
  "Old Mutual",
  "Colpensiones",
];

// ARL (Administradoras de Riesgos Laborales) en Colombia
export const ARL_COLOMBIA = [
  "Sura ARL",
  "Positiva ARL",
  "Colmena ARL",
  "Bolivar ARL",
  "Axa Colpatria ARL",
  "Liberty ARL",
  "Equidad Seguros ARL",
  "Alfa ARL",
  "Aurora ARL",
  "Colpatria ARL",
  "Mapfre ARL",
];

// Cajas de Compensacion Familiar en Colombia
export const CAJAS_COMPENSACION_COLOMBIA = [
  "Compensar",
  "Cafam",
  "Colsubsidio",
  "Comfandi",
  "Comfama",
  "Comfenalco Antioquia",
  "Comfenalco Valle",
  "Comfenalco Cartagena",
  "Comfenalco Santander",
  "Comfenalco Tolima",
  "Comfenalco Quindio",
  "Combarranquilla",
  "Cajacopi",
  "Comfacesar",
  "Comfachoco",
  "Comfacor",
  "Comfaguajira",
  "Comfahuila",
  "Comfamiliar Atlantico",
  "Comfamiliar Boyaca",
  "Comfamiliar Caldas",
  "Comfamiliar Camacol",
  "Comfamiliar Cartagena",
  "Comfamiliar Cundinamarca",
  "Comfamiliar Huila",
  "Comfamiliar Nariño",
  "Comfamiliar Risaralda",
  "Comfamiliar Sucre",
  "Comfanorte",
  "Comfaoriente",
  "Comfasucre",
  "Cofrem",
  "Comcaja",
  "Caja de Compensacion del Putumayo",
  "Caja de Compensacion del Amazonas",
];
